server:
  port: ${PORT:8761}   # ← cambia el 8761 fijo por esto

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${PORT:8761}/eureka/
  instance:
    prefer-ip-address: true